const dict = {
ru:{
navSolutions:"Решения",navServices:"Услуги",navProcess:"Как это работает",navVideos:"Видео",navContact:"Контакты",navCta:"Получить предложение",pageTitle:"VENDNOVA — Умные решения для вендинга",metaDescription:"VENDNOVA — умные решения для вендинга и автоматизированной торговли для бизнеса и частных клиентов по всей России. Подбор, поставка, установка и обслуживание.",
heroEyebrow:"ВЕНДИНГОВЫЕ РЕШЕНИЯ ПО ВСЕЙ РОССИИ",heroTitle:"Умные решения для вендинга и автоматизированной торговли.",heroText:"Вам не нужно выбирать из ограниченного каталога. Расскажите, что вам нужно — мы подберём оборудование и предложим решение под ваш проект.",
heroPrimary:"Расскажите, что вам нужно",heroSecondary:"Посмотреть решения",
trust1:"По всей России",trust2:"Подбор под задачу",trust3:"Связь онлайн",floatTitle:"Индивидуальный подбор",floatText:"Не ограничиваемся готовым каталогом",
anyEyebrow:"ЛЮБОЕ ОБОРУДОВАНИЕ. ЛЮБАЯ ЗАДАЧА.",anyTitle:"Не нашли нужное оборудование? Расскажите нам, что вам нужно.",anyText:"VENDNOVA не ограничивается готовым каталогом. Мы изучаем вашу задачу и предлагаем подходящее оборудование, комплектацию и формат поставки.",anyCard1:"У вас уже есть идея",anyCard1Text:"Опишите продукт, место установки и желаемый формат — мы подберём варианты.",anyLi1:"Поставка по всей России",anyLi2:"Оборудование под задачу",anyLi3:"Опциональная установка и настройка",anyCta:"Получить предложение →",anyCard2:"Вы ещё не знаете, что выбрать",anyCard2Text:"Расскажите нам о вашей цели — мы предложим решение для вашего пространства.",anyLi4:"Любая отрасль",anyLi5:"Индивидуальное брендирование",anyLi6:"Банковские карты, NFC, QR-коды и другие способы оплаты",anyCta2:"Обсудить задачу →",
privateTitle:"Для частных клиентов",privateText:"Хотите купить автомат или запустить вендинговый проект? Расскажите о месте, бюджете и продукте — мы предложим подходящие варианты.",privateLi1:"Покупка оборудования",privateLi2:"Доставка и установка",privateLi3:"Настройка и обучение",privateLi4:"Обслуживание по договорённости",
businessTitle:"Для бизнеса",businessText:"У вас есть пространство и конкретная задача? Мы изучим ваши потребности и предложим подходящее решение для вендинга, включая нестандартные форматы.",businessLi1:"Решения для любых отраслей",businessLi2:"Индивидуальное брендирование",businessLi3:"Безналичная оплата и QR",businessLi4:"Поставка, сервис и пополнение",learnMore:"Начать проект →",
storyEyebrow:"НЕ ПРОСТО МАШИНА",storyTitle:"Мы подбираем решение с учётом вашей задачи.",storyText:"Вам не нужно знать модель или технические характеристики заранее. Опишите, что хотите продавать, где будет установлено оборудование и кто будет им пользоваться.",story1:"Продукт и сценарий использования",story2:"Формат и техническая конфигурация",story3:"Поставка и запуск проекта",storyCta:"Получить предложение",
solEyebrow:"ВОЗМОЖНОСТИ",solTitle:"Какие решения мы предлагаем.",solText:"Ниже представлены основные направления. Это не ограниченный каталог: если нужной модели нет, расскажите нам о вашей задаче.",
s1:"Умный магазин / умный холодильник",s1p:"Автономные магазины и решения для автоматизированного хранения и продажи товаров.",s2:"Еда и напитки",s2p:"Готовая еда, снеки, напитки и свежие продукты.",s3:"Кофе и горячие напитки",s3p:"Кофейные решения и оборудование для продажи горячих напитков в разных локациях.",s4:"Специализированные решения",s4p:"Медицина, спорт, красота, электроника и другие ниши.",s5:"Индивидуальная разработка",s5p:"Нестандартный продукт или формат? Подберём подходящую конфигурацию.",s6:"Ваша идея",s6p:"Расскажите, что хотите автоматизировать. Мы найдём решение.",requestIt:"Запросить решение →",
servEyebrow:"ПОДДЕРЖКА ПРОЕКТА",servTitle:"От подбора оборудования до запуска.",servText:"Объём поддержки зависит от вашего проекта и согласованных условий сотрудничества.",
serv1:"Подбор",serv1p:"Изучаем задачу и предлагаем подходящие варианты.",serv2:"Доставка",serv2p:"Организуем поставку оборудования по России.",serv3:"Установка",serv3p:"Помогаем с размещением, подключением и запуском.",serv4:"Настройка",serv4p:"Настраиваем платёжные системы, интерфейс и параметры оборудования.",serv5:"Обучение",serv5p:"Предоставляем инструкции и объясняем, как пользоваться оборудованием.",serv6:"Сервис",serv6p:"Техническое обслуживание и ремонт — в соответствии с согласованными условиями.",
procEyebrow:"ПРОСТОЙ ПРОЦЕСС",procTitle:"От идеи до запуска оборудования.",procText:"Не знаете, какую модель выбрать? Это нормально. Сначала нам важно понять вашу задачу.",procCta:"Описать задачу",
step1:"Расскажите о задаче",step1p:"Что хотите продавать, где и для кого.",step2:"Мы подбираем варианты",step2p:"Проверяем доступные модели и комплектацию.",step3:"Согласуем предложение",step3p:"Цена, сроки, доставка и дополнительные услуги.",step4:"Поставляем и запускаем",step4p:"Организуем доставку и согласованные услуги.",
howEyebrow:"КАК ЭТО РАБОТАЕТ",howTitle:"Понятный путь от заявки до запуска проекта.",videoEyebrow:"ВИДЕО",videoTitle:"Посмотрите, как работают современные решения для вендинга.",videoText:"Видео помогает быстро понять возможности оборудования и формат использования.",videoOneTitle:"Решение для вендинга",videoOneText:"Пример современного оборудования и процесса покупки.",videoTwoTitle:"Другой формат",videoTwoText:"Дополнительный пример решения для вендинга.",payEyebrow:"УДОБНАЯ ОПЛАТА",payTitle:"Удобные способы оплаты для ваших клиентов.",payText:"В зависимости от модели и проекта оборудование может поддерживать оплату банковскими картами, через NFC и QR-коды, наличными и другими способами.",
reqEyebrow:"ПОЛУЧИТЬ ПРЕДЛОЖЕНИЕ",reqTitle:"Расскажите, что вам нужно.",reqText:"Оплата на сайте не производится. Сначала мы изучим ваш запрос, свяжемся с вами и предложим подходящие варианты.",
formPrivate:"Частный клиент",formBusiness:"Бизнес",fPrivateName:"Имя и фамилия",fCompanyName:"Название компании",fContact:"Контактное лицо",fIndustry:"Сфера деятельности",fName:"Имя / контактное лицо",fCompany:"Компания",fPhone:"Телефон",fCity:"Город",fTelegram:"Telegram",fCollab:"Формат сотрудничества",fCollabPlaceholder:"Выберите вариант",collabPurchase:"Покупка",collabRental:"Аренда",collabLeasing:"Лизинг / финансирование",collabPartnership:"Партнёрство",collabConsultation:"Не знаю — нужна консультация",fNeed:"Что вам нужно?",fSubmit:"Отправить запрос",fNote:"Нажимая кнопку, вы отправляете запрос в VENDNOVA. Оплата на сайте не производится.",phPrivateName:"Ваше имя и фамилия",phCompany:"Название компании",phContact:"Имя и фамилия",phPhone:"+7",phCity:"Москва",phTelegram:"@username",phIndustry:"Например: производство, гостиничный бизнес, розничная торговля",phNeed:"Опишите товар или услугу, место установки, количество оборудования и ваши пожелания",
contactEyebrow:"VENDNOVA",contactTitle:"Готовы обсудить ваш проект?",contactTelegram:"Telegram:",contactEmail:"Электронная почта:",footerText:"Умные решения для вендинга и автоматизированной торговли.",
faqEyebrow:"ЧАСТЫЕ ВОПРОСЫ", faqTitle:"Ответы на главные вопросы",
      faqIntro:"Если вы не нашли нужную информацию, свяжитесь с нами — мы обсудим ваш проект индивидуально.",
      faq1q:"Можно ли заказать оборудование, которого нет в каталоге?",
      faq1a:"Да. Расскажите, какое оборудование или решение вам необходимо, и мы подберём подходящий вариант.",
      faq2q:"Доставляете ли вы оборудование по всей России?",
      faq2a:"Да, мы осуществляем поставки по всей России. Стоимость и сроки доставки зависят от выбранного оборудования и региона.",
      faq3q:"Можно ли заказать индивидуальное решение?",
      faq3a:"Да. Для нестандартных задач мы можем разработать индивидуальную конфигурацию с учётом внешнего вида, функциональности и способов оплаты.",
      faq4q:"Есть ли новое и бывшее в употреблении оборудование?",
      faq4a:"Мы можем предложить новое или бывшее в употреблении оборудование в зависимости от вашего запроса и наличия подходящих моделей.",
      faq5q:"Какие способы оплаты поддерживает оборудование?",
      faq5a:"В зависимости от модели оборудование может поддерживать оплату банковскими картами, через NFC и QR-коды, а также наличными и другими способами.",
      faq6q:"Предоставляете ли вы услуги по установке и настройке?",
      faq6a:"Да, мы можем организовать установку, настройку и обучение в зависимости от выбранного оборудования и формата сотрудничества.",
      faq7q:"Кто занимается обслуживанием и ремонтом?",
      faq7a:"Условия обслуживания определяются договором. Обслуживание и ремонт могут выполняться нами, клиентом или предоставляться как дополнительная услуга.",
      faq8q:"Возможны ли аренда, лизинг или партнёрство?",
      faq8a:"Возможность аренды, лизинга или партнёрства рассматривается индивидуально в зависимости от оборудования, проекта и региона.",
      faq9q:"Как узнать стоимость?",
      faq9a:"Стоимость зависит от модели оборудования, комплектации и условий поставки. Оставьте заявку, и мы подготовим предложение с учётом ваших требований.",
      faq10q:"Какой срок поставки?",
      faq10a:"Срок поставки зависит от выбранного оборудования, его доступности, производства и региона доставки. После уточнения проекта мы сообщим ориентировочные сроки.",
      faqCta:"Не нашли ответа?", faqButton:"Обсудить мой проект"
},
en:{
navSolutions:"Solutions",navServices:"Services",navProcess:"How it works",navVideos:"Videos",navContact:"Contact",navCta:"Get a quote",pageTitle:"VENDNOVA — Smart Vending Solutions",metaDescription:"VENDNOVA provides smart vending and automated retail solutions across Russia, including equipment selection, delivery, installation and service.",
heroEyebrow:"VENDING SOLUTIONS ACROSS RUSSIA",heroTitle:"Smart vending solutions for business.",heroText:"You do not need to choose from a limited catalogue. Tell us what you need — we will match the equipment and propose a solution for your project.",
heroPrimary:"Tell us what you need",heroSecondary:"Explore solutions",
trust1:"Across Russia",trust2:"Need-based selection",trust3:"Online support",floatTitle:"Tailored selection",floatText:"Not limited to a fixed catalogue",
anyEyebrow:"ANY EQUIPMENT. ANY NEED.",anyTitle:"Do not see the machine you need? Tell us what you are looking for.",anyText:"VENDNOVA is not limited to a fixed catalogue. We study your needs and propose the right equipment, configuration and delivery format.",anyCard1:"You already have an idea",anyCard1Text:"Tell us the product, location and desired format — we will find suitable options.",anyLi1:"Delivery across Russia",anyLi2:"Equipment matched to your need",anyLi3:"Optional installation and setup",anyCta:"Get a proposal →",anyCard2:"You are not sure what to choose",anyCard2Text:"Tell us your goal and we will propose a solution for your space.",anyLi4:"Any industry",anyLi5:"Custom branding",anyLi6:"Card, NFC, QR and other payment options",anyCta2:"Discuss your need →",
privateTitle:"For private clients",privateText:"Want to buy a machine or launch a vending project? Tell us about the location, budget and product — we will propose suitable options.",privateLi1:"Equipment purchase",privateLi2:"Delivery and installation",privateLi3:"Setup and training",privateLi4:"Maintenance by agreement",
businessTitle:"For business",businessText:"Have a space and a specific need? We study your requirements and propose a vending solution, including custom formats.",businessLi1:"Solutions for any industry",businessLi2:"Custom branding",businessLi3:"Card, NFC and QR payments",businessLi4:"Supply, service and restocking",learnMore:"Start a project →",
storyEyebrow:"MORE THAN A MACHINE",storyTitle:"We build the solution around your need.",storyText:"You do not need to know the model or technical specifications in advance. Tell us what you want to sell, where it will be installed and who will use it.",story1:"Product and use case",story2:"Format and technical configuration",story3:"Delivery and project launch",storyCta:"Get a proposal",
solEyebrow:"POSSIBILITIES",solTitle:"Examples of solutions we can provide.",solText:"These are examples, not a limited catalogue. If you do not see what you need, simply describe the idea.",
s1:"Smart Store / Smart Fridge",s1p:"Autonomous stores and smart refrigeration solutions.",s2:"Food & beverages",s2p:"Ready meals, snacks, drinks and fresh products.",s3:"Coffee & hot drinks",s3p:"Coffee and beverage solutions for different locations.",s4:"Specialized solutions",s4p:"Healthcare, fitness, beauty, electronics and other niches.",s5:"Custom development",s5p:"Unusual product or format? We can source a suitable configuration.",s6:"Your idea",s6p:"Tell us what you want to automate. We will find a solution.",requestIt:"Request a solution →",
servEyebrow:"PROJECT SUPPORT",servTitle:"From equipment to launch.",servText:"Support depends on your project and the agreed contract.",
serv1:"Selection",serv1p:"We study your need and propose suitable options.",serv2:"Delivery",serv2p:"We organize equipment delivery across Russia.",serv3:"Installation",serv3p:"We help with placement, connection and launch.",serv4:"Configuration",serv4p:"Payment systems, interface and equipment setup.",serv5:"Training",serv5p:"We provide instructions and explain the equipment.",serv6:"Service",serv6p:"Maintenance and repair under the agreed service model.",
procEyebrow:"SIMPLE PROCESS",procTitle:"From idea to a working machine.",procText:"Not sure which model to choose? That is fine. Understanding your need comes first.",procCta:"Describe your need",
step1:"Tell us about the need",step1p:"What you want to sell, where and for whom.",step2:"We find options",step2p:"We check available models and configurations.",step3:"We agree the proposal",step3p:"Price, timing, delivery and additional services.",step4:"We deliver and launch",step4p:"We organize delivery and the agreed services.",
howEyebrow:"HOW IT WORKS",howTitle:"A clear path from request to launch.",videoEyebrow:"VIDEO",videoTitle:"See how modern vending solutions work.",videoText:"These videos help you quickly understand the equipment and possible use cases.",videoOneTitle:"Vending solution",videoOneText:"An example of modern equipment and a user scenario.",videoTwoTitle:"Another format",videoTwoText:"An additional vending example for inspiration.",payEyebrow:"MODERN PAYMENTS",payTitle:"Support for convenient payment methods.",payText:"Depending on the model and project, equipment can support cards, NFC, QR codes, cash and mobile scenarios.",
reqEyebrow:"GET A PROPOSAL",reqTitle:"Tell us what you need.",reqText:"There is no online payment. We first review your request, then contact you and propose options.",
formPrivate:"Private client",formBusiness:"Business",fPrivateName:"Full name",fCompanyName:"Company name",fContact:"Contact person",fIndustry:"Business activity",fName:"Name / Contact person",fCompany:"Company",fPhone:"Phone",fCity:"City",fTelegram:"Telegram",fCollab:"Cooperation format",fCollabPlaceholder:"Select an option",collabPurchase:"Purchase",collabRental:"Rental",collabLeasing:"Leasing / financing",collabPartnership:"Partnership",collabConsultation:"Not sure — I need advice",fNeed:"What do you need?",fSubmit:"Send request",fNote:"By submitting, you send a request to VENDNOVA. No payment is made on the website.",phPrivateName:"Your full name",phCompany:"Company name",phContact:"Full name",phPhone:"+7",phCity:"Moscow",phTelegram:"@username",phIndustry:"For example: manufacturing, hotel, retail",phNeed:"Describe the product, location, quantity and your requirements",
contactEyebrow:"VENDNOVA",contactTitle:"Ready to discuss your project.",contactTelegram:"Telegram:",contactEmail:"Email:",footerText:"Smart vending solutions for business.",
faqEyebrow:"FAQ", faqTitle:"Answers to common questions",
      faqIntro:"If you cannot find the information you need, contact us and we will discuss your project individually.",
      faq1q:"Can I order a vending machine that is not shown on the website?",
      faq1a:"Yes. Tell us what machine or solution you need and we will try to find a suitable option.",
      faq2q:"Do you deliver across Russia?",
      faq2a:"Yes, we consider deliveries throughout Russia. Delivery cost and timing depend on the equipment and destination.",
      faq3q:"Can I order a customized solution?",
      faq3a:"Yes. For specific requirements, we can consider customized configuration, appearance, functionality and payment options.",
      faq4q:"Do you offer new and used vending machines?",
      faq4a:"We can offer new or used options depending on your request and the availability of suitable equipment.",
      faq5q:"What payment methods can the machines support?",
      faq5a:"Depending on the model, options may include bank cards, contactless payments, QR codes, cash and other methods.",
      faq6q:"Do you provide installation and setup?",
      faq6a:"Yes. Installation, setup and training can be arranged depending on the agreed cooperation model.",
      faq7q:"Who handles maintenance and repairs?",
      faq7a:"This is defined by the contract. Maintenance can be handled by us, by the client, or offered as an additional service.",
      faq8q:"Do you offer rental, leasing or partnership options?",
      faq8a:"These options may be available. Terms are considered individually based on the equipment, project and region.",
      faq9q:"How do I get a price?",
      faq9a:"We do not use one fixed price for every project. Submit a request, tell us what you need and we will prepare a proposal.",
      faq10q:"How long does delivery take?",
      faq10a:"Timing depends on the selected equipment, availability, production and destination. We will provide an estimated timeframe after reviewing the project.",
      faqCta:"Did not find your answer?", faqButton:"Discuss my project"
}};
let lang="ru", mode="private", formMode="private";
const updateMediaLanguage=()=>{
  const ruImg=document.getElementById("howImageRu"), enImg=document.getElementById("howImageEn");
  if(ruImg&&enImg){ruImg.classList.toggle("active",lang==="ru");enImg.classList.toggle("active",lang==="en");}
  const ids=[["videoOne","mlt1mxOU2I4"],["videoTwo","MbF_syEOu_E"]];
  ids.forEach(([id,vid])=>{const f=document.getElementById(id);if(f)f.src=`https://www.youtube.com/embed/${vid}?rel=0&modestbranding=1&playsinline=1&hl=${lang==="ru"?"ru":"en"}`;});
};
const applyLang=()=>{document.documentElement.lang=lang;const meta=document.querySelector('meta[name="description"]');if(meta&&dict[lang].metaDescription)meta.content=dict[lang].metaDescription;document.getElementById("langBtn").innerHTML=(lang==="ru"?"RU":"EN")+" <span>⌄</span>";document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(dict[lang][k])el.textContent=dict[lang][k]});document.querySelectorAll("[data-alt-ru]").forEach(el=>{const a=lang==="ru"?el.dataset.altRu:el.dataset.altEn;if(a)el.alt=a});document.querySelectorAll("input,textarea").forEach(el=>{
  const key=el.dataset.placeholder;
  if(key && dict[lang][key]) el.placeholder=dict[lang][key];
});
document.querySelectorAll("select option[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(dict[lang][k])el.textContent=dict[lang][k]});
document.querySelectorAll(".payment-pills span").forEach((el,i)=>{if(lang==="en"){el.textContent=["Bank cards","NFC","QR","Cash","Mobile payments"][i]}else{el.textContent=["Банковские карты","NFC","QR-коды","Наличные","Другие способы оплаты"][i]}});
};
document.getElementById("langBtn").onclick=()=>document.getElementById("langMenu").classList.toggle("open");
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>{lang=b.dataset.lang;document.getElementById("langMenu").classList.remove("open");applyLang()});
document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));document.querySelectorAll(".form-mode-btn").forEach(x=>x.classList.toggle("active",x.dataset.formMode===mode));formMode=mode});
document.querySelectorAll("[data-mode-link]").forEach(a=>a.onclick=()=>{mode=a.dataset.modeLink;document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));document.querySelectorAll(".form-mode-btn").forEach(x=>x.classList.toggle("active",x.dataset.formMode===mode))});
document.querySelectorAll(".form-mode-btn").forEach(b=>b.onclick=()=>{formMode=b.dataset.formMode;document.querySelectorAll(".form-mode-btn").forEach(x=>x.classList.toggle("active",x.dataset.formMode===formMode));const biz=formMode==="business";document.querySelectorAll(".business-only").forEach(x=>{x.hidden=!biz;const input=x.querySelector("input");if(input) input.required=biz});document.querySelectorAll(".private-only").forEach(x=>{x.hidden=biz;const input=x.querySelector("input");if(input) input.required=!biz});});
document.getElementById("leadForm").addEventListener("submit",e=>{e.preventDefault();const r=document.getElementById("formResult"), f=e.currentTarget, data=new FormData(f), biz=formMode==="business";const collab=data.get("collaboration");const collabLabel=collab?((dict[lang]["collab"+collab.charAt(0).toUpperCase()+collab.slice(1)])||collab):"";const client=biz?(data.get("company")||""):(data.get("name")||"");const contact=biz?(data.get("contact_person")||""):client;const title=lang==="ru"?"Заявка принята":"Request received";const msg=lang==="ru"?"Спасибо! Ваша заявка отправлена. Мы изучим запрос и свяжемся с вами после его рассмотрения.":"Thank you! Your request has been submitted. We will review it and contact you after reviewing your request.";r.hidden=false;r.innerHTML=`<strong>${title}</strong><br>${msg}<br><br><small>${lang==="ru"?"Формат":"Format"}: ${collabLabel||"—"}${contact?`<br>${lang==="ru"?"Контакт":"Contact"}: ${contact}`:""}${data.get("city")?`<br>${lang==="ru"?"Город":"City"}: ${data.get("city")}`:""}</small>`;f.reset();document.querySelectorAll(".business-only").forEach(x=>{x.hidden=true;const input=x.querySelector("input");if(input) input.required=false});document.querySelectorAll(".private-only").forEach(x=>{x.hidden=false;const input=x.querySelector("input");if(input) input.required=true});formMode="private";document.querySelectorAll(".form-mode-btn").forEach(x=>x.classList.toggle("active",x.dataset.formMode==="private"));applyLang();});
updateMediaLanguage();applyLang();
